# Generated by Django 6.0.6 on 2026-09-27 11:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('EQUITY', 'Equity')], max_length=20)),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('tax_treatment', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ledger.account')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='ledger.campus')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=120)),
                ('account_title', models.CharField(max_length=140)),
                ('account_number', models.CharField(max_length=80)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('ledger_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_profile', to='ledger.account')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='ledger.campus')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(blank=True, max_length=3)),
                ('role_name', models.CharField(max_length=80)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('approval_level', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.campus')),
            ],
            options={
                'ordering': ['approval_level', 'minimum_amount'],
            },
        ),
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_centres', to='ledger.campus')),
            ],
            options={
                'ordering': ['campus__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SOFT_CLOSED', 'Soft closed'), ('LOCKED', 'Locked')], default='OPEN', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=120)),
                ('project', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='ledger.account')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='ledger.campus')),
                ('cost_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='ledger.costcentre')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='ledger.financialperiod')),
            ],
            options={
                'ordering': ['period__start_date', 'account__code'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('voucher_type', models.CharField(choices=[('RV', 'Receipt voucher'), ('PV', 'Payment voucher'), ('JV', 'Journal voucher'), ('CV', 'Contra voucher'), ('CN', 'Credit note'), ('DN', 'Debit note')], max_length=3)),
                ('voucher_date', models.DateField(default=datetime.date.today)),
                ('party_name', models.CharField(blank=True, help_text='Customer, vendor or employee name', max_length=160)),
                ('narration', models.TextField()),
                ('source_module', models.CharField(default='Manual', max_length=80)),
                ('source_reference', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='vouchers/%Y/%m/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Pending approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_vouchers', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='ledger.campus')),
                ('cost_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='ledger.costcentre')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='ledger.financialperiod')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_vouchers', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_voucher', to='ledger.voucher')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voucher_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('STATEMENT', 'Bank statement'), ('CONTRACT', 'Contract'), ('TAX', 'Tax document'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ledger.voucher')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('reference', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_lines', to='ledger.bankaccount')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('matched_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_matches', to='ledger.voucher')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('POST', 'Post'), ('REVERSE', 'Reverse'), ('EXPORT', 'Export'), ('PERIOD', 'Period'), ('RECONCILE', 'Reconcile'), ('UPLOAD', 'Upload')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='ledger.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='ledger.account')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.voucher')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_name', models.CharField(max_length=100)),
                ('session_date', models.DateField(default=datetime.date.today)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('receipts', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('payments', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('physical_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('variance_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending approval'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='ledger.campus')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('campus', 'counter_name', 'session_date'), name='uniq_cash_session_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='costcentre',
            constraint=models.UniqueConstraint(fields=('campus', 'code'), name='uniq_cost_centre_code'),
        ),
        migrations.AddConstraint(
            model_name='financialperiod',
            constraint=models.UniqueConstraint(fields=('start_date', 'end_date'), name='uniq_period_range'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['status', 'voucher_date'], name='ledger_vouc_status_83b9db_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['campus', 'voucher_date'], name='ledger_vouc_campus__6b2daf_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['source_module', 'source_reference'], name='ledger_vouc_source__a43f4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.UniqueConstraint(fields=('bank_account', 'transaction_date', 'reference'), name='uniq_bank_statement_ref'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='bank_line_one_positive_side'),
        ),
        migrations.AddConstraint(
            model_name='voucherline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='voucher_line_one_positive_side'),
        ),
    ]
